from app.models import db, Post, User, environment, SCHEMA


def seed_posts():
    user_2_posts = [
        Post(
            user_id=2,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=2,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=2,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=2,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=2,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=2,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=2,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=2,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=2,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=2,
            post_type="",
            title="",
            text=""
        ),
    ]

    user_3_posts = [
        Post(
            user_id=3,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=3,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=3,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=3,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=3,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=3,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=3,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=3,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=3,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=3,
            post_type="",
            title="",
            text=""
        ),
    ]

    user_4_posts = [
        Post(
            user_id=4,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=4,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=4,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=4,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=4,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=4,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=4,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=4,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=4,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=4,
            post_type="",
            title="",
            text=""
        ),
    ]

    user_5_posts = [
        Post(
            user_id=5,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=5,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=5,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=5,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=5,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=5,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=5,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=5,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=5,
            post_type="",
            title="",
            text=""
        ),
        Post(
            user_id=5,
            post_type="",
            title="",
            text=""
        ),
    ]

    for post in user_2_posts:
        db.session.add(post)

    for post in user_3_posts:
        db.session.add(post)

    for post in user_4_posts:
        db.session.add(post)

    for post in user_5_posts:
        db.session.add(post)

    db.session.commit()


def undo_posts():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.posts RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM posts")

    db.session.commit()
